# Generated by Django 3.1.7 on 2021-04-03 19:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Lot',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('total_spaces', models.IntegerField(default=0)),
                ('available_spaces', models.IntegerField(default=0)),
                ('available_spaces_lrg', models.IntegerField(default=0)),
                ('reserved_spaces', models.IntegerField(default=0)),
                ('location', models.CharField(default='', max_length=10000)),
                ('nickname', models.CharField(default='', max_length=10000)),
                ('price', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='Reservation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('license_plate', models.CharField(default='', max_length=8)),
                ('lot', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='parkingapp.lot')),
            ],
        ),
    ]
