# Generated by Django 3.1.7 on 2021-02-24 22:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Lot',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('total_spaces', models.IntegerField(default=0)),
                ('available_spaces', models.IntegerField(default=0)),
                ('reserved_spaces', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='Space',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_reserved', models.BooleanField(default=False)),
                ('cost', models.IntegerField(default=0)),
                ('lot', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='parkingapp.lot')),
            ],
        ),
    ]
