# Generated by Django 3.1.7 on 2021-04-03 19:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('parkingapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='reservation',
            name='email',
            field=models.EmailField(default='', max_length=254),
        ),
        migrations.AddField(
            model_name='reservation',
            name='name',
            field=models.CharField(default='', max_length=100),
        ),
    ]
