# Generated by Django 3.1.7 on 2021-04-14 18:09

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('parkingapp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='', max_length=100)),
                ('date', models.DateField()),
                ('location', models.CharField(default='', max_length=1000)),
            ],
        ),
        migrations.CreateModel(
            name='EventSpaces',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('total_spaces', models.IntegerField(default=0)),
                ('available_spaces', models.IntegerField(default=0)),
                ('available_spaces_lrg', models.IntegerField(default=0)),
                ('location', models.CharField(default='', max_length=10000)),
                ('nickname', models.CharField(default='', max_length=10000)),
                ('price', models.IntegerField(default=0)),
                ('Event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='parkingapp.event')),
            ],
        ),
        migrations.CreateModel(
            name='Reservation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='', max_length=100)),
                ('email', models.EmailField(max_length=254)),
                ('license_plate', models.CharField(default='', max_length=8)),
                ('lot', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='parkingapp.eventspaces')),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.RemoveField(
            model_name='space',
            name='lot',
        ),
        migrations.DeleteModel(
            name='Lot',
        ),
        migrations.DeleteModel(
            name='Space',
        ),
    ]
