# Generated by Django 3.1.7 on 2021-03-21 01:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('parkingapp', '0004_delete_space'),
    ]

    operations = [
        migrations.AddField(
            model_name='lot',
            name='available_spaces_lrg',
            field=models.IntegerField(default=0),
        ),
    ]
