# Generated by Django 3.1.7 on 2021-03-22 03:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('parkingapp', '0005_lot_available_spaces_lrg'),
    ]

    operations = [
        migrations.CreateModel(
            name='Reservation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('license_plate', models.CharField(default=0, max_length=8)),
                ('lot', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='parkingapp.lot')),
            ],
        ),
    ]
