# Generated by Django 3.1.7 on 2021-04-01 16:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('parkingapp', '0008_reservation_email'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reservation',
            name='license_plate',
            field=models.CharField(default='', max_length=8),
        ),
    ]
