# Generated by Django 3.1.7 on 2021-04-06 02:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('parkingapp', '0009_auto_20210401_0913'),
    ]

    operations = [
        migrations.AddField(
            model_name='lot',
            name='price',
            field=models.IntegerField(default=0),
        ),
    ]
