# Generated by Django 3.1.7 on 2021-04-09 21:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('parkingapp', '0010_lot_price'),
    ]

    operations = [
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='', max_length=100)),
                ('date', models.DateField()),
                ('location', models.CharField(default='', max_length=1000)),
            ],
        ),
        migrations.CreateModel(
            name='EventSpaces',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('total_spaces', models.IntegerField(default=0)),
                ('available_spaces', models.IntegerField(default=0)),
                ('available_spaces_lrg', models.IntegerField(default=0)),
                ('location', models.CharField(default='', max_length=10000)),
                ('nickname', models.CharField(default='', max_length=10000)),
                ('price', models.IntegerField(default=0)),
                ('Event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='parkingapp.event')),
            ],
        ),
        migrations.AlterField(
            model_name='reservation',
            name='lot',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='parkingapp.eventspaces'),
        ),
        migrations.DeleteModel(
            name='Lot',
        ),
    ]
