# Generated by Django 3.1.7 on 2021-04-11 19:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('parkingapp', '0011_auto_20210409_1436'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='reservation',
            name='date',
        ),
    ]
