# Generated by Django 3.1.7 on 2021-04-14 22:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('parkingapp', '0014_reservation_space_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reservation',
            name='space_type',
            field=models.CharField(choices=[('std', 'Standard'), ('lrg', 'Large')], max_length=10),
        ),
    ]
