# Generated by Django 3.1.7 on 2021-04-15 02:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('parkingapp', '0015_auto_20210414_1536'),
        ('parkingapp', '0008_delete_user'),
    ]

    operations = [
    ]
