# Generated by Django 3.1.7 on 2021-04-18 03:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('parkingapp', '0017_auto_20210417_2011'),
    ]

    operations = [
        migrations.AddField(
            model_name='reservation',
            name='event',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='parkingapp.event'),
            preserve_default=False,
        ),
    ]
