# Generated by Django 3.1.7 on 2021-04-18 03:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('parkingapp', '0018_reservation_event'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='reservation',
            name='event',
        ),
    ]
